#
# DAL Deployment script for openSuSe Leap 42.1
# Copyright (c) 2016, Diversity Arrays Technology, All rights reserved.
#
# Author: Puthick Hok
# Date: 08/08/2016
# Usage: ansible-playbook kddart_dal_v2_4_0_server_deployment_leap-42.1.yml
# Description: By running the usage command, ansible will install and configure DAL
#              according the instructions in kddart_server_deployment_centos7.yml.
#              This script needs to be run by root.
#              For more information about how to read and write an ansible playbook,
#              please refer to ansible documentation on the web.
#

- name: Install KDDArT on host machine
  hosts: kddartserver
  gather_facts: no

  vars_prompt:
    - name: "local_tar_gz_file"
      prompt: "Enter the source tar.gz file of KDDart wih either relative or full path."
      private: no
  
    - name: "dbpass"
      prompt: "Password for kddart_dal user"
      private: yes

    - name: "ip_network"
      prompt: "Enter IP network of the target machine, eg. 192.168.78.0/24"
      private: no

  vars:
    src_file:  /root/KDDArT-DAL-v2.4.0.tar.gz
    dal_version: v2.4.0
    dal_db_version: v2_4_0
    local_dir: /root/KDDArT-DAL-{{ dal_version }}
    apache_base_dir: /srv/www
    local_src_dir: /usr/local
    force_tasks: True
    monetdbpass: monetdb
    postgrespass: '{{ dbpass }}'
    dal_address_name: kddart.example.com
    solr_workspace: /root/tmp_install_solr
    solr_config_file: /etc/default/solr.in.sh
    solr_install_dir: /opt
    solr_home: /var/solr
    solr_version: "6.2.1"
    mysql_jdbc_jar: mysql-connector-java-*-bin.jar
    monetdb_jdbc_jar: monetdb-jdbc-*.jar

  tasks:
    
    - name: Add zypper repo from Geo 
      shell: >
        if [ ! `zypper lr | grep 'Geo'` ]; then
        zypper ar --no-gpgcheck http://download.opensuse.org/repositories/Application:/Geo/openSUSE_Leap_42.1 Geo;
        fi;

    - name: Install supporting binaries
      zypper: pkg={{item}} state=present disable_gpg_check=yes
      with_items:
        - make
        - bison
        - gcc
        - perl
        - curl
        - apache2
        - apache2-mod_perl-2.0.9
        - perl-App-cpanminus
        - mysql-community-server
        - mysql-devel
        - perl-DBD-Pg
        - perl-DBD-mysql
        - perl-Archive-Zip
        - perl-Net-SSLeay
        - perl-IO-Socket-SSL
        - perl-XML-DOM
        - perl-XML-Parser
        - perl-XML-LibXML
        - postgresql94
        - postgresql94-server
        - postgresql-init
        - postgresql-contrib
        - postgresql94-postgis
        - shapelib
        - libshp-devel
        - pcre
        - pcre-devel
        - libxml2
        - libxml2-devel
        - java-1_8_0-openjdk
        - libopenssl-devel
        - pcre-devel
        - libxml2-devel
        - acl

    - name: Remove nagios-www (its apache config is not Apache 2.4 ready)
      zypper: pkg=nagios-www state=absent

    - name: Copy the tar.gz file
      copy: src={{ local_tar_gz_file }} dest={{ src_file }}

    - name: Create local_dir
      shell: >
        if [ ! -d {{ local_dir }} ]; then
        mkdir -p {{ local_dir }};
        fi

    - name: Untar and decompress KDDart source
      shell: >
        if [ -d {{ local_dir }} ]; then 
        cd {{ local_dir }};
        tar -zxvf {{ src_file }} --strip 1;
        fi;

    - name: Install cpanm
      shell: curl -L https://cpanmin.us | perl - App::cpanminus
      register: bash_result
      changed_when: "bash_result.rc != 0"

    - name: Install Perl Libraries used in DAL
      cpanm: name={{item}}
      with_items:
        - Parse::PMFile
        - DBI
        - DBD::SQLite
        - Geo::Coder::Google
        - Text::CSV
        - Text::CSV_XS
        - Text::CSV::Simple
        - DateTime::Format::MySQL
        - DateTime::Format::Pg
        - Email::Valid
        - Config::Simple
        - Apache2_4::AuthCookie
        - Crypt::Random
        - Color::Calc
        - Apache::Htpasswd
        - Authen::Simple
        - CGI::Application
        - CGI::Application::Dispatch
        - CGI::Application::Plugin::AutoRunmode
        - CGI::Application::Plugin::ActionDispatch
        - CGI::Application::Plugin::DevPopup
        - CGI::Application::Plugin::Session
        - Log::Log4perl
        - Net::OAuth2::Client
        - Net::OAuth2::AccessToken
        - Mozilla::CA
        - Tree::R
        - JSON::XS
        - Hash::Merge
        - XML::Simple
        - XML::Writer
        - XML::Parser::PerlSAX
        - File::Lockfile
        - JSON::Validator
        - String::Random
        - String::Escape
        - XML::XSLT
        - UNIVERSAL::require
        - Apache::Solr
        - MCE
        - MCE::Shared
       
    - name: Install Geo::Shapelib manually 
      shell: >
        cd /tmp;
        curl -L http://www.cpan.org/authors/id/A/AJ/AJOLMA/Geo-Shapelib-0.21.tar.gz | tar zx;
        cd /tmp/Geo-Shapelib-0.21;
        perl -w Makefile.PL --shapelib=/usr/lib64/libshp.so;
        make install;
        rm -rf /tmp/Geo-Shapelib-0.21

    - name: Install CGI::Application::Plugin::Authentication manually
      shell: >
        cd /tmp;
        curl -L http://www.cpan.org/authors/id/S/SI/SILASMONK/CGI-Application-Plugin-Authentication-0.20.tar.gz | tar zx;
        cd /tmp/CGI-Application-Plugin-Authentication-0.20;
        perl -w Makefile.PL;
        make install;
        rm -rf /tmp/CGI-Application-Plugin-Authentication-0.20

    - name: Install XML::Checker manually
      shell: >
        cd /tmp;
        curl -L http://search.cpan.org/CPAN/authors/id/T/TJ/TJMATHER/XML-Checker-0.13.tar.gz | tar zx;
        cd /tmp/XML-Checker-0.13;
        perl -w Makefile.PL;
        make;
        make install;
        rm -rf /tmp/XML-Checker-0.13

    - name: Install monetdb manually
      shell: >
        if [ ! -e /usr/local/bin/monetdbd ]; then
        cd {{local_src_dir}};
        curl --insecure -L https://www.monetdb.org/downloads/sources/archive/MonetDB-11.19.9.tar.bz2 | tar jx;
        cd {{local_src_dir}}/MonetDB-11.19.9;
        {{local_src_dir}}/MonetDB-11.19.9/configure --disable-jdbc;
        make;
        make install;
        cd {{local_src_dir}}/MonetDB-11.19.9/clients/perl;
        make;
        make install;
        cp -rp {{local_src_dir}}/lib/perl5/vendor_perl/5.18.2/x86_64-linux-thread-multi/* /usr/lib/perl5/vendor_perl/5.18.2/x86_64-linux-thread-multi/;
        rm -rf {{local_src_dir}}/MonetDB-11.19.9;
        cp {{local_dir}}/other/kddart.mal /usr/local/lib64/monetdb5/autoload;
        fi;

    - name: Start monetdb service
      shell: >
        ldconfig;
        mkdir -p /var/lib/monetdb;
        [[ -d /var/lib/monetdb/dbfarm ]] || /usr/local/bin/monetdbd create /var/lib/monetdb/dbfarm;
        [[ `pidof /usr/local/bin/monetdbd` -gt 1 ]] || /usr/local/bin/monetdbd start /var/lib/monetdb/dbfarm;

    - service: name=postgresql state=started

    - name: Configure PostgreSQL access permission settings
      shell: >
        mv /var/lib/pgsql/data/pg_hba.conf /var/lib/pgsql/data/pg_hba_conf`date +'%Y%m%d'`;
        echo 'local   all             all                                   trust' > /var/lib/pgsql/data/pg_hba.conf;
        echo 'host    all             all             127.0.0.1/32          trust' >> /var/lib/pgsql/data/pg_hba.conf;
        echo 'host    all             all             ::1/128               trust' >> /var/lib/pgsql/data/pg_hba.conf;
        echo 'host    kddart_gis_enviro_{{ dal_db_version }}  all           {{ ip_network }}        password' >> /var/lib/pgsql/data/pg_hba.conf;
        echo 'host    kddart_gis_enviro_{{ dal_db_version }}  all           127.0.0.1/24            password' >> /var/lib/pgsql/data/pg_hba.conf;

    - service: name=mysql state=started

    - name: Disable sql_mode
      shell: >
        echo "set global sql_mode='NO_ENGINE_SUBSTITUTION'" | mysql -u root;
        [[ `grep 'sql_mode' /etc/my.cnf` ]] && sed -i 's|sql_mode=.*|sql_mode=NO_ENGINE_SUBSTITUTION|' /etc/my.cnf;

    - service: name=postgresql state=restarted

    - service: name=mysql state=restarted

    - name: Append Marker SQL group_concat def
      shell: echo 'CREATE AGGREGATE group_concat(t text) RETURNS text external name "kddart"."group_concat";' >> {{ local_dir }}/other/db_files/kddart_marker_dal_{{ dal_version }}.sql

    - name: Adjust create_dbs.sh update the password
      shell: >
        sed -i "s|DB_PASS='yourSecurePassword'|DB_PASS='{{ dbpass }}'|g" {{ local_dir }}/other/create_dbs.sh;

    - name: Create KDDart Databases
      shell: "{{ local_dir }}/other/create_dbs.sh 1 kddart_gis_enviro_{{ dal_db_version }} {{ local_dir }}/other/db_files/kddart_gis_enviro_dal_{{ dal_version }}_postgis2.sql kddart_{{ dal_db_version }} {{ local_dir }}/other/db_files/kddart_dal_{{ dal_version }}.sql kddart_marker_{{ dal_db_version }} {{ local_dir }}/other/db_files/kddart_marker_dal_{{ dal_version }}.sql 1"

    - name: Make host entry
      shell: "[[ `grep '{{ dal_address_name }}' /etc/hosts` ]] || echo \"`ip route get 1 | awk '{print $NF;exit}'`  {{ dal_address_name }}\" >> /etc/hosts"

    - name: Copy apache configuration
      shell: "[[ -f /etc/apache2/vhosts.d/http-kddart.example.com.conf ]] || cp {{local_dir}}/other/http-kddart.example.com.conf /etc/apache2/vhosts.d"

    - name: Create directories
      file: path={{ item }} state=directory owner=wwwrun group=www mode=0755
      with_items:
        - '{{ apache_base_dir }}/cgi-bin/kddart'
        - '{{ apache_base_dir }}/tmp/kddart'
        - '{{ apache_base_dir }}/perl-lib'
        - '{{ apache_base_dir }}/vhosts'
        - '{{ apache_base_dir }}/vhosts/{{ dal_address_name }}'
        - '{{ apache_base_dir }}/session/kddart'
        - '{{ apache_base_dir }}/secure'
        - '{{ apache_base_dir }}/vhosts/{{ dal_address_name }}/storage'
        - '{{ apache_base_dir }}/vhosts/{{ dal_address_name }}/storage/multimedia'

    - name: Create monetdb password file
      shell: "[[ -f {{ apache_base_dir }}/secure/monetdb_user.txt ]] || echo \"username = monetdb\npassword = {{ monetdbpass }}\" > {{ apache_base_dir }}/secure/monetdb_user.txt"

    - name: Create mysql password file
      shell: "[[ -f {{ apache_base_dir }}/secure/mysql_user.txt ]] || echo \"username = kddart_dal\npassword = {{ dbpass }}\" > {{ apache_base_dir }}/secure/mysql_user.txt"

    - name: Create postgres password file
      shell: "[[ -f {{ apache_base_dir }}/secure/postgres_user.txt ]] || echo \"username = kddart_dal\npassword = {{ dbpass }}\" > {{ apache_base_dir }}/secure/postgres_user.txt"

    - name: Copy files to the relevant direcotries - due to * it needs in one line
      shell: >
        cp -rp {{ local_dir }}/vhosts/kddart.example.com/* {{ apache_base_dir }}/vhosts/{{ dal_address_name }};
        cp -rp {{ local_dir}}/perl-lib/* {{ apache_base_dir }}/perl-lib;
        cp {{local_dir}}/other/kddart_dal.cfg {{ apache_base_dir }}/secure;
        cp {{local_dir}}/cgi-bin/kddart/* {{ apache_base_dir }}/cgi-bin/kddart;

    - name: Change /tmp/kddart to {{ apache_base_dir }}/tmp/kddart (Apache2.4 cannot write to /tmp)
      shell: sed -i "s|/tmp/kddart/|{{ apache_base_dir }}/tmp/kddart/|" {{ apache_base_dir }}/secure/kddart_dal.cfg;

    - name: Change owner to wwwrun
      shell: chown wwwrun:www {{ apache_base_dir }}/vhosts/{{ dal_address_name }} -Rf

    - name: Update base URL for test cases
      shell: echo "http://{{ dal_address_name }}/dal" > {{ local_dir }}/other/whitebox_test_cases/TestSuite/dal_base_url.conf

    - name: Add perl module load to sysconfig
      shell: "[[ `grep 'APACHE_MODULES=.*perl' /etc/sysconfig/apache2` ]] || a2enmod perl"

    - name: Add headers module load to sysconfig
      shell: "[[ `grep 'APACHE_MODULES=.*headers' /etc/sysconfig/apache2` ]] || a2enmod headers"

    - name: Change ACL for tmp directory
      shell: >
        setfacl -d -m o::rx {{ apache_base_dir }}/tmp/kddart;
        setfacl -d -m g::rwx {{ apache_base_dir }}/tmp/kddart;

    - name: Restart mysql
      shell: systemctl restart mysql

    - name: Restart postgresql
      shell: systemctl restart postgresql

    - name: Restart monetdb
      shell: >
        [[ `pidof /usr/local/bin/monetdbd` -gt 1 ]] && /usr/local/bin/monetdbd stop /var/lib/monetdb/dbfarm;
        sleep 30s;
        /usr/local/bin/monetdbd start /var/lib/monetdb/dbfarm;

    - name: Make MonetDB start by default at boot time
      shell: >
        [[ `grep '/usr/local/bin/monetdbd start' /etc/rc.d/after.local` ]] || echo "/usr/local/bin/monetdbd start /var/lib/monetdb/dbfarm" >> /etc/rc.d/after.local;
        chmod u+x /etc/rc.d/after.local;
        systemctl enable local;

    - name: Restart apache
      shell: systemctl restart apache2

    - name: Make mysql start on reboot
      shell: systemctl enable mysql

    - name: Make postgresql start on reboot
      shell: systemctl enable postgresql

    - name: Make apache2 start on reboot
      shell: systemctl enable apache2

    - name: Create JAVA Home environment variable
      shell: "[[ `grep 'export JAVA_HOME' /etc/bash.bashrc` ]] || echo 'export JAVA_HOME=/usr/lib64/jvm/java-1.8.0-openjdk-1.8.0/jre' >> /etc/bash.bashrc"

    - name: Run export for JAVA Home for this session
      shell: export JAVA_HOME=/usr/lib64/jvm/java-1.8.0-openjdk-1.8.0/jre

    - name: Create Java Classpath environment variable
      shell: "[[ `grep 'export CLASSPATH' /etc/bash.bashrc` ]] || echo 'export CLASSPATH=$JAVA_HOME/lib' >> /etc/bash.bashrc"

    - name: Run export for Java Classpath for this session
      shell: export CLASSPATH=$JAVA_HOME/lib

    - name: Create Solr working directory
      file: path={{ solr_workspace }} state=directory

    - name: Download Solr
      get_url:
        url: "http://archive.apache.org/dist/lucene/solr/{{ solr_version }}/solr-{{ solr_version }}.tgz"
        dest: "{{ solr_workspace }}/solr-{{ solr_version }}.tgz"
        force: no

    - name: Expand Solr
      unarchive:
        src: "{{ solr_workspace }}/solr-{{ solr_version }}.tgz"
        dest: "{{ solr_workspace }}"
        creates: "{{ solr_workspace }}/solr-{{ solr_version }}/CHANGES.txt"
        copy: no

    - name: Run Solr installation script
      shell: >
        {{ solr_workspace }}/solr-{{ solr_version }}/bin/install_solr_service.sh
        {{ solr_workspace }}/solr-{{ solr_version }}.tgz
        -i {{ solr_install_dir }}
        -d {{ solr_home }} -f
        creates={{ solr_install_dir }}/solr/bin/solr

    - name: Check current list of Solr cores
      uri:
        url: http://localhost:8983/solr/admin/cores
        return_content: yes
      register: solr_cores_current

    - name: Create configured cores.
      shell: "su solr -c '{{ solr_install_dir }}/solr/bin/solr create_core -c {{ item }}'"
      when: "'{{ item }}' not in '{{ solr_cores_current.content }}'"
      with_items:
        - db
        - monetdb
        - dal

    - name: Insert config into db core solrconfig.xml
      blockinfile:
        dest: "{{ solr_home }}/data/db/conf/solrconfig.xml"
        marker: "<!-- {mark} DART ANSIBLE MANAGED BLOCK -->"
        insertafter: "<config>"
        content: |
            <lib dir="${solr.install.dir}/dist/" regex="solr-dataimporthandler-.*\.jar" />
            <lib dir="${solr.install.dir:../../../..}/contrib/dataimporthandler-extras/lib/" regex=".*\.jar" /> 
            <requestHandler name="/dataimport" class="org.apache.solr.handler.dataimport.DataImportHandler">
              <lst name="defaults">
               <str name="config">db-data-config.xml</str>
              </lst>
            </requestHandler>

    - name: Insert config into monetdb core solrconfig.xml
      blockinfile:
        dest: "{{ solr_home }}/data/monetdb/conf/solrconfig.xml"
        marker: "<!-- {mark} DART ANSIBLE MANAGED BLOCK -->"
        insertafter: "<config>"
        content: |
            <lib dir="${solr.install.dir}/dist/" regex="solr-dataimporthandler-.*\.jar" />
            <lib dir="${solr.install.dir:../../../..}/contrib/dataimporthandler-extras/lib/" regex=".*\.jar" /> 
            <requestHandler name="/dataimport" class="org.apache.solr.handler.dataimport.DataImportHandler">
              <lst name="defaults">
                <str name="config">monetdb-data-config.xml</str>
              </lst>
            </requestHandler>

    - name: copy data-config.xml for each core
      shell: cp {{ local_dir }}/other/solr/config/{{ item }}/conf/{{ item }}-data-config.xml {{ solr_home }}/data/{{ item }}/conf
      with_items:
        - db
        - monetdb
        - dal

    - name: Copy MySQL jdbc jar files
      shell: cp -f {{ local_dir }}/other/solr/dataimporthandler/*.jar {{ solr_install_dir }}/solr/contrib/dataimporthandler-extras/lib

    - name: Configure core db
      shell: >
        {{ local_dir }}/other/solr/{{ item }}-setup-fields.sh 1>{{ local_dir }}/{{ item }}-setup-fields.log 2>&1
      with_items:
        - db
        - monetdb
        - dal

    - name: Put the password into db-data-config.xml
      replace: dest={{ solr_home }}/data/db/conf/db-data-config.xml regexp='yourSecurePassword' replace="{{ dbpass }}"
    - name: Change unique key from id to SolrId
      replace: dest={{ solr_home }}/data/{{ item }}/conf/managed-schema regexp='<uniqueKey>id</uniqueKey>' replace="<uniqueKey>SolrId</uniqueKey>"
      with_items:
        - db
        - monetdb
        - dal

    - name: Restart solr
      shell: /etc/init.d/solr restart

    - cron:
        name: Reindex Solr
        minute: "*/15"
        job: "/usr/bin/perl -w {{ local_dir }}/other/solr/reindex_solr.pl --dalbaseurl 'http://{{ dal_address_name }}/dal' --workingdir '/tmp' --username 'admin' --password 'kddartadmin' --kddartgroup 0 --solrhost 
    'http://localhost' 
    --solrport '8983' --solrcorecsv 'dal,db,monetdb' > /root/reindex_solr.log 2>&1"
